'''
This node parses string messages from the sensor board into SensorData messages for use by the rest of the system

Topics
 Subscribes to:
- /vehicle/sensor_data_str
    - String
 Publishes to:
- /vehicle/sensor_data
    - SensorData custom msg type

Parameters: 
- verbose (bool, default: false)
    - Whether to log all parsed data in the console
    - Useful for debugging but a lot of clutter / overhead for normal operation
'''

# Packages for ROS2
import rclpy
from rclpy.node import Node

# ROS2 message definitions
from vehicle_interfaces.msg import SensorData
from std_msgs.msg import String
import importlib          # Used to dynamically resolve message classes for nested parsing

# Vehicle codes from config files
import os
from ament_index_python.packages import get_package_share_directory
import yaml


class VehicleSensorStringParser(Node):
    def __init__(self):
        super().__init__('vehicle_sensor_string_parser')
        self.get_logger().info('Starting Vehicle Sensor String Parser Node')

        # Expected execution parameters
        self.declare_parameter('verbose', False)  # Whether to log all parsed data in the console

        # Load codes, delimiters, and special encoding parameters once at startup
        package_share = get_package_share_directory('vehicle_string_converter')
        sensor_config_path = os.path.join(package_share, 'config', 'sensor_codes.yaml')
        delimiter_config_path = os.path.join(package_share, 'config', 'delimiters.yaml')
        encoding_config_path = os.path.join(package_share, 'config', 'sensor_encoding.yaml')

        try:
            with open(sensor_config_path, 'r') as f:
                self.sensor_codes = yaml.safe_load(f)
            with open(delimiter_config_path, 'r') as f:
                self.delimiters = yaml.safe_load(f)
            with open(encoding_config_path, 'r') as f:
                self.encodings = yaml.safe_load(f)

        except Exception as e:
            # The control system can't run without the codes, but sensors can still run
            self.get_logger().error(
                f"Error loading sensor files; system will be unable to interface with sensor board: {e}"
            )
            rclpy.shutdown()
            return

        self.get_logger().info("Successfully loaded sensor codes")

        # Cache for schema expansion (prevents repeated recursion work)
        self._schema_cache = {}

        # Recursively generate data type and encoding mappings for quick access during parsing
        self.fields_and_types = self.expand_schema(SensorData)

        # Build encoding mapping that matches the data types structure
        self.fields_and_encodings = self.build_encodings(
            self.fields_and_types,
            self.encodings
        )

        # Subscriber to vehicle sensor string messages
        self.sensor_subscriber = self.create_subscription(
            String,
            '/vehicle/sensor_data_str',
            self.sensor_callback,
            10
        )

        # Publisher for sensor data formatted messages
        self.sensor_string_publisher = self.create_publisher(
            SensorData,
            '/vehicle/sensor_data',
            10
        )

    # All the message schema stuff was generated by ChatGPT and needs to be tested
    def resolve_msg_class(self, type_str):
        type_str = type_str.replace("[]", "")

        pkg, msg = type_str.split("/")
        module = importlib.import_module(f"{pkg}.msg")

        return getattr(module, msg)

    def expand_schema(self, msg_class):

        msg_name = msg_class.__name__

        if msg_name in self._schema_cache:
            return self._schema_cache[msg_name]

        schema = {}

        for field, ros_type in msg_class._fields_and_field_types.items():

            base_type = ros_type.replace("[]", "")

            if "/" in base_type:  # nested message
                try:
                    sub_class = self.resolve_msg_class(base_type)

                    schema[field] = self.expand_schema(sub_class)

                except Exception as e:
                    self.get_logger().warn(
                        f"Failed to resolve nested type '{base_type}': {e}"
                    )
                    schema[field] = ros_type

            else:
                schema[field] = ros_type  # primitive

        self._schema_cache[msg_name] = schema
        return schema

    def build_encodings(self, type_tree, override_tree):

        enc = {}

        for field, value in type_tree.items():

            if isinstance(value, dict):
                enc[field] = self.build_encodings(
                    value,
                    override_tree.get(field, {})
                )
            else:
                enc[field] = override_tree.get(field, "int")  # default HERE

        return enc


    def sensor_callback(self, msg):
        # Convert the string message to a SensorData message
        sensor_data = self.convert(msg)
        # Publish the SensorData message
        if sensor_data:  # Only publish if conversion was successful
            self.sensor_string_publisher.publish(sensor_data)
            if self.get_parameter('verbose').get_parameter_value().bool_value:
                self.get_logger().info(f"Published sensor data update: {sensor_data}")
        else:
            self.get_logger().error("Failed to convert sensor data message to SensorData format")


    def convert(self, msg):
        # Declare output type SensorData
        sensor_data = SensorData()
        # Get the string from the incoming message
        sensor_string = msg.data

        # First, check for valid packet delimiters
        start_delimiter = self.delimiters.get('packet_start', '')
        end_delimiter = self.delimiters.get('packet_end', '')
        # Makes sure delimiters aren't empty to avoid edge case
        if start_delimiter and end_delimiter:
            if not sensor_string.startswith(start_delimiter) or not sensor_string.endswith(end_delimiter):
                self.get_logger().error(f"Invalid sensor data message received: missing start/end delimiter")
                return None
        else:
            self.get_logger().error("Packet delimiters not defined in config files; unable to validate incoming messages")
            return None

        # Verify the data start and end delimiter
        data_start_delimiter = self.delimiters.get('field_start', '')
        data_end_delimiter = self.delimiters.get('field_end', '')
        if not data_start_delimiter or not data_end_delimiter:
            self.get_logger().error("Data delimiters not defined in config files; unable to validate incoming messages")
            return None

        # After checking the packet delimiters, strip them
        # (there existence has already been validated so they can safely be removed without additional checks)
        sensor_string = sensor_string[len(start_delimiter):len(sensor_string) - len(end_delimiter)]

        # Now split the string into components based on data delimiters
        data_strings = {}
        while sensor_string:
            # The code runs up to but not including the next data start delimiter
            split_index_start = sensor_string.find(data_start_delimiter)
            if split_index_start == -1:
                break  # No more data start delimiters, exit the loop
            split_index_end = split_index_start + len(data_start_delimiter)
            end_index = sensor_string.find(data_end_delimiter, split_index_end)
            if end_index == -1:
                self.get_logger().error(f"Invalid sensor data message format: the last data in the packet was missing its end delimiter")
                break  # No more data end delimiters, exit the loop
            
            # Get the next code and data substrings and store them in the command_strings dict
            next_code = sensor_string[:split_index_start]  # Get the substring before the next data start delimiter
            next_code = next_code.strip()  # Remove any leading/trailing whitespace from the code  
            next_data = sensor_string[split_index_end:end_index]  # Get the substring after the next data start delimiter

            # Only store if a code is present
            if not next_code:
                self.get_logger().warn("Empty sensor code encountered, skipping")
            else:
                data_strings[next_code] = next_data  # Store the code and its corresponding data substring
            
            # Strip the processed part of the string for the next iteration
            sensor_string = sensor_string[end_index + len(data_end_delimiter):]
            

        # Make sure there was valid data found in the command string
        if not data_strings:
            self.get_logger().error(f"Invalid sensor data message format: no valid data strings found")
            return None
        
        # Convert each piece of data into appropriate datatype and assign it to the corresponding field in the SensorData message
        # This needs to happen recursively to handle nested message types
        data_parsed = False  # Flag to track if at least one piece of data was successfully parsed
        for next_code, next_data in data_strings.items():
            # Get the corresponding field name from the config file
            sensor_name = self.sensor_codes.get(next_code)
            # Make sure it is a valid sensor code form config file
            if not sensor_name:
                self.get_logger().warn(f"Unrecognized sensor code '{next_code}' in sensor data message; skipping this field")
                continue
            # Convert the value to the appropriate datatype based on the field type and assign it to the corresponding field in the ControlFeedback message
            try: 
                # Convert and assign to the corresponding SensorData field
                value, is_array = self.construct_data_field(sensor_name, next_data)
                field_obj = getattr(sensor_data, sensor_name)
                if is_array:
                    field_obj.append(value)
                else:
                    setattr(sensor_data, sensor_name, value)
                data_parsed = True  # Set the flag to True if at least one piece of data was successfully parsed
            except Exception as e:
                self.get_logger().error(f"Error converting value for {sensor_name}: {e}")
                continue  # Skip this field but continue parsing others
            except ValueError as e:
                self.get_logger().error(f"Error parsing sensor data message for {sensor_name}: {e}")
                continue  # Skip this field but continue parsing others
        
        if not data_parsed:
            self.get_logger().warn("No valid data found in sensor data message")
            return None  # Return None if no valid data was parsed, otherwise return the ControlFeedback message
        
        return sensor_data


    def construct_data_field(self, sensor_name, data_str):
        # This handles the extraction of data and appropriate type conversion for a sensor data field
        

    # This function must be updated to handle each datatype possible in a message
    def string_to_ros_type(self, value_str, ros_type):
        try:
            if ros_type == 'boolean':
                return value_str.lower() in ['1', 'true']
            elif ros_type.startswith('int') or ros_type.startswith('uint'):
                return int(value_str)
            elif ros_type.startswith('float'):
                return float(value_str)
            elif ros_type == 'string':
                return value_str
            else:
                self.get_logger().warn(f"Unknown type '{ros_type}', treating as string")
                return value_str
        except Exception as e:
            self.get_logger().error(f"Failed to convert '{value_str}' to {ros_type}: {e}")
            return None


def main(args=None):
    rclpy.init(args=args)
    node = VehicleControlStringParser()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()