# This file maps buttons from an IR remote control to vehicle commands

# Only the filled in fields will be used to interpert the command
# Address not required, use any to ignore
# Command and / or data is required, leave empty to ignore

# command:
#  address:
#   command    :     int_val
#   data       :     int_val

# Special to reduce error messages from known interference
# Will be parsd as a list 
ignore:
  any:
    command: [64]

# For remote AIWA RC-6AS20
# The buttons are in order left to right, top to bottom

# Numbered button panel

set_speed_10:
 any:
   data: 1016

set_speed_20:
 any:
   data: 1012

set_speed_30:
 any:
   data: 1008


set_speed_40:
 any:
   data: 1004

set_speed_50:
 any:
   data: 1000

set_speed_60:
 any:
   data: 996


set_speed_70:
 any:
   data: 992

set_speed_80:
  any:
    data: 988

set_speed_90:
  any:
    data: 984


set_speed_0:
 any:
   data: 980

set_speed_100:
  any:
    data: 976

set_direction_forward:
 any:
   data: 908


# shift_toggle:
# Broken button, using a different one

toggle_direction:
  any:
    data: 729

set_direction_reverse:
  any:
    data: 661



# Playback control panel

stop:
  any:
    data: 749

set_steering_left-100:
  any:
    data: 753

set_steering_right-100:
  any:
    data: 757


go:
  any:
    data: 745

coast:
  any:
    data: 761

toggle_hold_speed:
  any:
    data: 765


# reset:
# Replace broken button
toggle_shift:
  any:
    data: 900

increment_speed_down-10:
  any:
    data: 709

increment_speed_up-10:
  any:
    data: 713
