# Keep track of special sensor data encodings so they can be decoded properly by the parser
# If no encoding is specified, the parser will default to the ros type of the corresponding field
# It will know what data type it is casting to and will properly handle this
# For example hex can go to int, float, etc. and will be decoded appropriately based on the ros field type

# *** Determines what to do if the recieved data encoding doesn't exactly match the ros data type

# Note: MUST ensure floats are truncated to the correct number of decial places and converted to ints

# Sensor parameter         :     encoding

arduino_timestamp         :     "hex"

encoder:
  arduino_timestamp        :     "hex_timestamp_offset"
  direction                :     "unsigned_direction" 
  position                 :     "hex"
  velocity                 :     "hex"

gps:
  arduino_timestamp        :     "hex_timestamp_offset"
  position                 :     "hex_float_6"
  heading                  :     "hex_float_2"
  speed_kmph               :     "hex_float_2"
  gps_time                 :     "hex"
  sats                     :     "hex"

ir_remote:
  arduino_timestamp        :     "hex_timestamp_offset"
  address                  :     "hex"
  command                  :     "hex"
  data                     :     "hex"

mpu:
  arduino_timestamp        :     "hex_timestamp_offset"
  imu                      :     "hex_float_2" 
  temp                     :     "hex_float_2"

qmc:
  arduino_timestamp        :     "hex_timestamp_offset"
  mag                      :     "hex" 
  heading                  :     "hex"
  temp                     :     "hex_float_2"

temperature:
  arduino_timestamp        :     "hex_timestamp_offset"
  temp                     :     "hex_float_2"

tof:
  arduino_timestamp        :     "hex_timestamp_offset"
  range                    :     "hex"
  intensity                :     "hex"

ultrasonic:
  arduino_timestamp        :     "hex_timestamp_offset"
  range                    :     "hex"