# This converts from the sensor index provided by the arduino to a frame ID for use in the message header

encoder:
  "0"    :      "steering_encoder"

gps:
  "0"     :     "gps"

ir_remote:
  "0"     :     "ir_remote"

mpu:
  "0"     :     "mpu_front"
  "1"     :     "mpu_back"

qmc:
  "0"     :     "qmc"

temperature:
  "0"     :     "external_temperature"

tof:
  "0"     :     "tof_front-left"
  "1"     :     "tof_front-right"
  "2"     :     "tof_left"
  "3"     :     "tof_right"

ultrasonic:
  "0"     :     "ultrasonic_front-left"
  "1"     :     "ultrasonic_front-right"
  "2"     :     "ultrasonic_left"
  "3"     :     "ultrasonic_back"
  "4"     :     "ultrasonic_right"