#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'vehicle-simulation','console_scripts','vehicle_sensor_sim'
__requires__ = 'vehicle-simulation'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('vehicle-simulation', 'console_scripts', 'vehicle_sensor_sim')()
    )
