# Keep track of special sensor data encodings so they can be decoded properly by the parser
# If no encoding is specified, the parser will default to the ros type of the corresponding field
# It will know what data type it is casting to and will properly handle this
# For example hex can go to int, float, etc. and will be decoded appropriately based on the ros field type

# *** Determines what to do if the recieved data encoding doesn't exactly match the ros data type

# Note: MUST ensure floats are truncated to the correct number of decial places and converted to ints
# For signed encodings, the sign "bit" is the most significant character in the hex string

# Sensor parameter         :     encoding

arduino_timestamp          :     "unsigned_hex"

encoder:
  arduino_timestamp        :     "hex_timestamp_offset"
  position                 :     "signed_hex"

gps:
  arduino_timestamp        :     "hex_timestamp_offset"
  position                 :     "signed_hex_float_6"
  altitude                 :     "signed_hex_float_2"
  heading                  :     "unsigned_hex_float_2"
  speed_kmph               :     "unsigned_hex_float_2"
  gps_time                 :     "unsigned_hex"
  sats                     :     "unsigned_hex"

ir_remote:
  arduino_timestamp        :     "hex_timestamp_offset"
  address                  :     "unsigned_hex"
  command                  :     "unsigned_hex"
  data                     :     "unsigned_hex"

mpu:
  arduino_timestamp        :     "hex_timestamp_offset"
  accel                    :     "signed_hex" 
  gyro                     :     "signed_hex" 
  temp                     :     "signed_hex"

qmc:
  arduino_timestamp        :     "hex_timestamp_offset"
  mag                      :     "signed_hex" 
  heading                  :     "unsigned_hex"

temperature:
  arduino_timestamp        :     "hex_timestamp_offset"
  temp                     :     "signed_hex_float_2"

tof:
  arduino_timestamp        :     "hex_timestamp_offset"
  range                    :     "hex"
  intensity                :     "hex"

ultrasonic:
  arduino_timestamp        :     "hex_timestamp_offset"
  range                    :     "hex"