#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'vehicle-networking','console_scripts','sensor_serial_interface'
__requires__ = 'vehicle-networking'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('vehicle-networking', 'console_scripts', 'sensor_serial_interface')()
    )
